# Generated by Django 6.0.3 on 2026-04-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.CharField(max_length=255)),
                ('meeting_location', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Meeting info',
                'verbose_name_plural': 'Meeting info',
            },
        ),
    ]
